language: java
jdk:
- oraclejdk8
env:
  global:
  - secure: I7Ks085o8O3CTjRxh6Idtt4a+omIwAjmPayolDCNgx72AoTXni1vH1p3JmH+B0mC7E0nLGIT0fDan8lN/kbHi3VlD4XK6XgEjNa+CaiNR3y5dwW5vK2as5b5iw2TmdN8WgsQ/YoPNCO/OA1CKnsebRY6E6B2C7gh3UCZfO5h/5F/uUSLXlEwtkyQy6CIAi0tdr74wYEGT2cV4sKFpslA2TZUOpH5xPZKa9RITZr9DX+FRAhF7eGyhhAx900uBdWZuOxvYTEqFl2EI3E3iqM6iKwYbKEWQodf793uqbMLWab+04btIq95qf9iu0SmZWBpF/ARwpykc89UqZrPD0H+9xD0uL/7qrL/fBD87xhP3kl8s0Nb2GiZY5C5IqSLp/jYw39s//tpp0L9XDMnmxZ5DO4HHAdpoDN3hi6D5KYXcOUbLDHFKOfr6Vh8EbaoHjGmTkL/Uao4KLRJilwGn1W6pTLTUE9WYmRmU1FzfFMgJYdcm8UBob6D6lyS9dBEJyKys6J3s/H4xVOUGKTXTFJ9dDrRHaGJET2+jSb29njN++MDizZp37VfWFZ2Q06LJaMYdWv1DmsiK69/JZXu6nwRFOXnZa6Kl9vIQgK2CC4+th2+lKznrTO2rSjZ7qQXOSatdeLr757aao4nYBlEasa3r1BAAvpkeOhljzeD2uKSnkY=
  - secure: j+i+l2PJD/WUZx2Y9IUH0Q/v4DKmLrULQKqXzpITbRadUN/MTFGVHyXfBzUNexy9fkNiOq1zkI4xWtIuHpaZlKh/oWlH0QW5if9AXueH+FEP3Ep54vjDkR+5Cq7nrtwAPaoubLjaBMC11CD1jEh5pRFaF4z3TbKh3zzkQg3jBJPY77oiwQwf8LKTiFrJN4fgkjJ0OZCUtzOppOd3cHfKEf4B3slpo9FdOyxjLw113CpmHetqEMNJOjPQpA07nU/YdvbH7ZljR9uhUg/TzBNOCjalNbnsLtkcAdCUTavizEg2GV0KsaHVcA/tfK9qtrnz7+WqC2B/UC+m1ZmJhd4m55QwBFmnJX5OcmIXRwUOnsirZmcl/RjqZUOVe3xpX3EKeOJLn8DuKuyf/KUIb4BFsGSVudix6Rn3bCbYbHPRnskdBsaoclVMIH4hImSE1Ii8VO609UxMroWrfvFs4oEZR4mpGYzqMr/DuwDuYC0/3LM3TxGpK7AhT1hex99xmbL+DQwFzc8mmAROg6fsnRZapQZ+6Bc6SlZZzZvxHn/FrdiIkis65t1sSUadpkszCeN1AvHr5R8Bvl3Ro+wZpNMixwRQf7GMPOsVEYoV4+VQ3346+zY8IhAQHOZxED+H0884IjVj5jHphnQcfcaaxkSMEvVJJv1xCVvLvrXattBSUZU=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- pip install --user codecov
after_success:
- codecov
- mvn clean deploy -DskipTests --settings .travis/maven-settings.xml
